version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todonet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - todonet

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - todonet

networks:
  todonet:
    driver: bridge

